spring.application.name=twitter-clone
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://mongodbuser:P%40%24%24w0rd@cluster1.rxepz.mongodb.net/twitter_db?retryWrites=true&w=majority
#mongodb://localhost:27017/twitter_db

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/

# Logging
logging.level.com.joshi.twitterclone=DEBUG

logging.level.org.springframework.security=DEBUG