spring.application.name=asmj-biz-connect

server.port=${PORT:8080}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=${UPLOAD_DIR:uploads/}

# Logging
logging.level.com.joshi.twitterclone=INFO
logging.level.org.springframework.security=INFO
# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
